FROM python:3.11-slim

WORKDIR /app

COPY tron_indexer/ ./tron_indexer/
COPY config/ ./config/
COPY run_indexer.py .

RUN pip install -r tron_indexer/requirements.txt

CMD ["python", "run_indexer.py"]
