FROM python:3.11-slim

WORKDIR /app

COPY forensic_suite/ ./forensic_suite/
COPY config/ ./config/

RUN pip install -r forensic_suite/requirements.txt

CMD ["python", "-m", "forensic_suite.trace_engine_v2"]
