[metadata]
name = forensic_suite_v2
version = 0.1.0
description = Unified multi-chain forensic suite
author = Louis
license = MIT

[options]
packages = find:
package_dir =
    = .
python_requires = >=3.10
install_requires =
    aiohttp
    asyncpg
    orjson
    prometheus_client
    psycopg2-binary
    python-dotenv
    PyYAML
    requests
    PySide6
    qt-material
    qasync
    pyqtgraph
    pillow

[options.packages.find]
where = forensic_suite_v2

[flake8]
max-line-length = 120
ignore = E302,E305,E501,F841
exclude = venv,.git,_pycache_,dashboards,grafana

[tool:pytest]
testpaths = tests