database:
  engine: "postgres"
  postgres:
    host: "localhost"
    port: 5432
    user: postgres
    password: Str0ngPassw0rd2025
    database: forensic

tron_rpc:
  base_urls:
    - "https://thrilling-orbital-smoke.tron-mainnet.quiknode.pro/ce1c2d934c05bee00e2c654bc5e07afd0a89a7f4/"
    - "https://stylish-virulent-waterfall.tron-mainnet.quiknode.pro/79e844fa55ba2064bba2454467cdec4e76dcedef/"
  timeout: 10
  max_retries: 3

eth_rpc:
  base_urls:
    - "https://fragrant-bitter-gadget.quiknode.pro/3a2c6082b3bb93a25a0ccda448f7a4d116d92e69/"
    - "https://powerful-weathered-sky.quiknode.pro/5ea5ab254db2e68c9f558128306d8f12e2605c97/"
  timeout: 10
  max_retries: 3

btc_rpc:
  base_urls:
    - "https://side-multi-haze.btc.quiknode.pro/9368eec255cd645e9db6104ff9c120fe12aa269c/"
    - "https://proud-proud-spring.btc.quiknode.pro/1c35abccd48420f178e9c6286844e3a9d27cd5e9/"
  timeout: 10
  max_retries: 3

indexer:
  start_block: 41400000
  batch_size: 100
  worker_threads: 2
  reorg_depth: 64
  mode: normal
  fast_sync_lookback: 0
  start_override: null

logging:
  level: "INFO"
  file: "C:/tron_indexer/logs/indexer.log"   # legacy / fallback if you still use it
  tron_log: "C:/tron_indexer/logs/tron_indexer.log"
  eth_log: "C:/tron_indexer/logs/eth_indexer.log"
  btc_log: "C:/tron_indexer/logs/btc_indexer.log"

chains:
  - tron
  # - eth
  # - btc


