database:
  engine: "postgres"
  postgres:
    host: "localhost"
    port: 5432
    user: "tron"
    password: "tronpass"
    database: "tron_index"

tron_rpc:
  base_url: "https://thrilling-orbital-smoke.tron-mainnet.quiknode.pro/ce1c2d934c05bee00e2c654bc5e07afd0a89a7f4/"
  timeout: 10
  max_retries: 3

eth_rpc:
  base_url: "https://fragrant-bitter-gadget.quiknode.pro/3a2c6082b3bb93a25a0ccda448f7a4d116d92e69/"
  timeout: 10
  max_retries: 3

btc_rpc:
  base_url: "https://side-multi-haze.btc.quiknode.pro/9368eec255cd645e9db6104ff9c120fe12aa269c/"
  timeout: 10
  max_retries: 3

indexer:
  start_block: 0
  batch_size: 50
  worker_threads: 2
  reorg_depth: 64
  mode: fast_sync
  fast_sync_lookback: 500000
  start_override: 23000000
  batch_size: 100

logging:
  level: "INFO"
  file: "C:/tron_indexer/logs/indexer.log"

chains:
  #- tron
  #- eth
  - btc

