apiVersion: 1

datasources:
  - name: ForensicPostgres
    type: postgres
    access: proxy
    url: host.docker.internal:5432
    user: forensic_user
    database: forensic_db
    isDefault: true
    jsonData:
      sslmode: "disable"
    secureJsonData:
      password: "CHANGE_ME"
