database:
  engine: "postgres"
  postgres:
<<<<<<< HEAD
    host: 127.0.0.1
=======
    host: 192.168.0.28
>>>>>>> master
    port: 5432
    user: postgres
    password: Str0ngPassw0rd2025
    database: forensic

btc_rpc:
  base_urls:
    - "https://side-multi-haze.btc.quiknode.pro/9368eec255cd645e9db6104ff9c120fe12aa269c/"
    - "https://proud-proud-spring.btc.quiknode.pro/1c35abccd48420f178e9c6286844e3a9d27cd5e9/"
  timeout: 10
  max_retries: 3

tron_rpc:
  base_urls: []
  timeout: 10
  max_retries: 3

eth_rpc:
  base_urls: []
  timeout: 10
  max_retries: 3

indexer:
  start_block: 0
  batch_size: 50
  worker_threads: 4
  reorg_depth: 6
  mode: normal
  fast_sync_lookback: 0
  start_override: null

logging:
  level: "INFO"
  file: "C:/forensic_suite_v2/logs/indexer.log"
  tron_log: "C:/forensic_suite_v2/logs/tron_indexer.log"
  eth_log: "C:/forensic_suite_v2/logs/eth_indexer.log"
  btc_log: "C:/forensic_suite_v2/logs/btc_indexer.log"

chains:
  - btc
